name: ci

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: ${{ matrix.platform }}

      - name: Available platforms
        run: echo "Building for ${{ matrix.platform }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Publish
        run: |
          docker buildx build --platform ${{ matrix.platform }} -t ankur512512/python-fastapi-userlogin:"$GITHUB_SHA-${{ matrix.platform }}" --push .
          echo -e "\n\nKindly use tag: $GITHUB_SHA-${{ matrix.platform }} in your deployment...\n\n"
